import { createFileRoute, Link } from "@tanstack/react-router";
import { Ambulance, Bell, ClipboardList, Plus, Upload, Users } from "lucide-react";
import { useCase } from "@/lib/case-store";
import { SectionHeader } from "@/components/section-header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/_app/nurse/dashboard")({
  head: () => ({
    meta: [
      { title: "Nurse Dashboard — PRATHAM" },
      { name: "description", content: "Operational intake and patient monitoring for nurses." },
    ],
  }),
  component: NurseDashboard,
});

function NurseDashboard() {
  const { activeEmergencyCount, pendingCount } = useCase();

  return (
    <div className="mx-auto max-w-7xl px-5 py-8 md:px-8">
      <SectionHeader
        eyebrow="Nurse station"
        title="Operational Dashboard"
        description="Fast intake, queue monitoring, and evidence handoff. The system forwards approval requests to doctors automatically."
        actions={
          <Button asChild size="sm">
            <Link to="/nurse/intake">
              <Plus className="mr-1.5 h-3.5 w-3.5" /> New intake
            </Link>
          </Button>
        }
      />

      <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <StatTile icon={Ambulance} label="Active emergencies" value={activeEmergencyCount} />
        <StatTile icon={Users} label="Intake pending" value={0} />
        <StatTile icon={Bell} label="Awaiting approval" value={pendingCount} />
        <StatTile icon={ClipboardList} label="Results in" value={0} />
      </div>

      <div className="mt-8 grid gap-6 lg:grid-cols-[1.4fr_1fr]">
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center justify-between text-sm font-semibold">
              Active emergency queue
              <span className="text-[11px] font-normal text-muted-foreground">
                0 patients
              </span>
            </CardTitle>
          </CardHeader>
          <CardContent className="p-0">
            <div className="p-8 text-center">
              <p className="text-sm text-muted-foreground">
                No patients in queue. Submit a new intake to begin.
              </p>
              <Button asChild size="sm" variant="outline" className="mt-4">
                <Link to="/nurse/intake">
                  <Plus className="mr-1.5 h-3.5 w-3.5" /> New intake
                </Link>
              </Button>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-semibold">Quick actions</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2">
            <ActionLink to="/nurse/intake" icon={Ambulance} label="New emergency intake" />
            <ActionLink to="/nurse/queue" icon={Users} label="Full patient queue" />
            <ActionLink to="/evidence" icon={Upload} label="Upload evidence" />
            <ActionLink to="/investigations" icon={ClipboardList} label="Investigation status" />
            <p className="pt-3 text-[11px] leading-relaxed text-muted-foreground">
              Investigation requests are generated by the system based on vitals + symptoms and
              forwarded to the on-call doctor automatically.
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

function StatTile({
  icon: Icon,
  label,
  value,
}: {
  icon: typeof Ambulance;
  label: string;
  value: number;
}) {
  return (
    <Card>
      <CardContent className="flex items-center gap-3 p-4">
        <div className="flex h-10 w-10 items-center justify-center rounded-md bg-primary/10 text-primary">
          <Icon className="h-5 w-5" />
        </div>
        <div>
          <p className="text-[11px] uppercase tracking-wider text-muted-foreground">{label}</p>
          <p className="font-display text-2xl font-semibold tabular-nums">{value}</p>
        </div>
      </CardContent>
    </Card>
  );
}

function ActionLink({
  to,
  icon: Icon,
  label,
}: {
  to: string;
  icon: typeof Ambulance;
  label: string;
}) {
  return (
    <Link
      to={to}
      className="flex items-center gap-3 rounded-md border bg-card px-3 py-2.5 text-sm transition-colors hover:bg-muted/60"
    >
      <Icon className="h-4 w-4 text-primary" />
      <span className="flex-1">{label}</span>
      <span className="text-xs text-muted-foreground">→</span>
    </Link>
  );
}
